services:
  postgres:
    image: postgres:15
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1900
      POSTGRES_DB: crypto_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: crypto_grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: